##Atha.contigs.fa is generated by Hifiasm
##AthaHiC_100000_abs.bed, AthaHiC_100000.matrix, AthaHiC_100000_iced.matrix are generated by HiC-pro using Atha.contigs.fa as the reference genome

gzip -d Atha.contigs.fa.gz

##get contig length
perl ../../fastaDeal.pl -attr id:len Atha.contigs.fa > Atha.contigs.fa.len 

##draw contig Hi-C heatmaps with 10*100000 (1-Mb) resolution
../../matrix2heatmap.py AthaHiC_100000_abs.bed AthaHiC_100000.matrix 10

##Run one round, when the contig assembly is quite good
perl ../../endhic.pl Atha.contigs.fa.len AthaHiC_100000_abs.bed AthaHiC_100000.matrix AthaHiC_100000_iced.matrix

ln Round_A.04.summary_and_merging_results/z.EndHiC.A.results.summary.cluster* ./


##convert cluster file to agp file
perl ../../cluster2agp.pl Round_A.04.summary_and_merging_results/z.EndHiC.A.results.summary.cluster Atha.contigs.fa.len > Atha.scaffolds.agp

##get final scaffold sequence file
perl ../../agp2fasta.pl Atha.scaffolds.agp Atha.contigs.fa > Atha.scaffolds.fa

##draw HiC heatmaps for scaffolds with 10*100000 (1-Mb) resolution
../../cluster2bed.pl AthaHiC_100000_abs.bed z.EndHiC.A.results.summary.cluster > clusterA_100000_abs.bed 2> clusterA.id.len
../../matrix2heatmap.py clusterA_100000_abs.bed AthaHiC_100000.matrix 10

##Here, Arabidopsis thalina has 5 chromosomes, and all these chromosomes can be successfully scaffolded by EndHiC
