##Atha.contigs.fa is generated by Hifiasm
##AthaHiC_100000_abs.bed, AthaHiC_100000.matrix, AthaHiC_100000_iced.matrix are generated by HiC-pro

gzip -d Atha.contigs.fa.gz

##get contig length
perl ../fastaDeal.pl -attr id:len Atha.contigs.fa > Atha.contigs.fa.len 

##Run one round, when the contig assembly is quite good
perl ../endhic.pl Atha.contigs.fa.len AthaHiC_100000_abs.bed AthaHiC_100000.matrix AthaHiC_100000_iced.matrix

##Run multiple rounds, when the contig assembly is not so good
perl ../endhic_auto.pl --rounds 3 Atha.contigs.fa.len AthaHiC_100000_abs.bed AthaHiC_100000.matrix AthaHiC_100000_iced.matrix

##convert cluster file to agp file
perl ../cluster2agp.pl 04.summary_and_merging_results/z.EndHiC.A.results.summary.cluster Atha.contigs.fa.len > Atha.scaffolds.agp

##get final scaffold sequence file
perl ../agp2fasta.pl Atha.scaffolds.agp Atha.contigs.fa > Atha.scaffolds.fa
